# Generated by Django 2.1.4 on 2018-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(default=True, max_length=128),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(default=True, max_length=128),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='middle_name',
            field=models.CharField(default=True, max_length=128),
        ),
    ]
