# Generated by Django 2.1.4 on 2018-12-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20181227_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(default=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(default=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(default=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='middle_name',
            field=models.CharField(default=True, max_length=128),
        ),
    ]
