# Generated by Django 2.1.4 on 2019-02-18 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20181227_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подписки'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(default=True, max_length=128, verbose_name='Емейл'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(default=True, max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(default=True, max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='message',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='middle_name',
            field=models.CharField(default=True, max_length=128, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования'),
        ),
    ]
