# Generated by Django 2.1.4 on 2019-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka_sudia', '0002_auto_20190220_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka_sudia',
            name='message',
            field=models.TextField(default=True, max_length=512, null=True, verbose_name='Сообщение'),
        ),
    ]
