# Generated by Django 2.1.4 on 2019-05-14 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=True, max_length=128, verbose_name='Емейл')),
                ('first_name', models.CharField(default=True, max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(default=True, max_length=128, verbose_name='Фамилия')),
                ('middle_name', models.CharField(default=True, max_length=128, verbose_name='Отчество')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Муж.'), ('f', 'Жен.')], max_length=1, null=True, verbose_name='Пол')),
                ('phone', models.CharField(default=True, max_length=18, verbose_name='Номер телефона')),
                ('weight', models.DecimalField(decimal_places=2, default=True, max_digits=6, verbose_name='Вес по заявке')),
                ('age', models.DecimalField(decimal_places=0, default=True, max_digits=2, verbose_name='Возраст')),
                ('country', models.CharField(default=True, max_length=32, verbose_name='Страна')),
                ('region', models.CharField(default=True, max_length=32, verbose_name='Область/Регион')),
                ('town', models.CharField(default=True, max_length=32, verbose_name='Город')),
                ('sostav', models.CharField(default=True, max_length=32, verbose_name='Команда/Лично')),
                ('trener', models.CharField(blank=True, max_length=32, verbose_name='Тренер')),
                ('message', models.TextField(default=None, max_length=128, null=True, verbose_name='Сообщение')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявления')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Он-лайн заявка на участие в турнире',
                'verbose_name_plural': 'Он-лайн заявки на участие в турнире',
            },
        ),
    ]
