# Generated by Django 2.1.4 on 2018-12-27 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=True, max_length=128)),
                ('first_name', models.CharField(default=True, max_length=128)),
                ('last_name', models.CharField(default=True, max_length=128)),
                ('middle_name', models.CharField(default=True, max_length=128)),
                ('phone', models.CharField(default=True, max_length=18)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
