# Generated by Django 2.1.4 on 2019-01-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zayavka',
            options={'verbose_name': 'Он-лайн заявка на участие в турнире', 'verbose_name_plural': 'Он-лайн заявки на участие в турнире'},
        ),
        migrations.AddField(
            model_name='zayavka',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=3),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='message',
            field=models.TextField(blank=True, default=True, null=True),
        ),
    ]
