# Generated by Django 2.1.4 on 2019-01-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0002_auto_20190107_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=6),
        ),
    ]
