# Generated by Django 2.1.4 on 2019-01-31 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0003_auto_20190107_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='age',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=2, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявления'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='email',
            field=models.EmailField(default=True, max_length=128, verbose_name='Емейл'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='first_name',
            field=models.CharField(default=True, max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='last_name',
            field=models.CharField(default=True, max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='message',
            field=models.TextField(blank=True, default=None, max_length=128, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='middle_name',
            field=models.CharField(default=True, max_length=128, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='phone',
            field=models.CharField(default=True, max_length=18, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=6, verbose_name='Вес по заявке'),
        ),
    ]
