# Generated by Django 2.1.4 on 2019-02-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0004_auto_20190131_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='town',
            field=models.CharField(default=True, max_length=32, verbose_name='Город'),
        ),
    ]
