# Generated by Django 2.1.4 on 2019-02-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0005_zayavka_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='country',
            field=models.CharField(default=True, max_length=32, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='region',
            field=models.CharField(default=True, max_length=32, verbose_name='Область/Регион'),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='sostav',
            field=models.CharField(default=True, max_length=32, verbose_name='Коанда/Лично'),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='trener',
            field=models.CharField(default=False, max_length=32, verbose_name='Тренер'),
        ),
    ]
