# Generated by Django 2.1.4 on 2019-02-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0006_auto_20190218_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='sostav',
            field=models.CharField(default=True, max_length=32, verbose_name='Команда/Лично'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='trener',
            field=models.CharField(default=None, max_length=32, verbose_name='Тренер'),
        ),
    ]
