# Generated by Django 2.1.4 on 2019-06-23 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_auto_20190515_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletes',
            name='discipline',
        ),
        migrations.AddField(
            model_name='athletes',
            name='discipline',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.Discipline', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='status',
            field=models.ForeignKey(default=1712567360, on_delete=django.db.models.deletion.CASCADE, to='athletes.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='weight_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.Weight_category', verbose_name='Вес. категория'),
        ),
        migrations.AlterField(
            model_name='athletesimage',
            name='Athletes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.Athletes', verbose_name='Спортсмен'),
        ),
    ]
