# Generated by Django 2.1.4 on 2019-06-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0008_auto_20190623_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletes',
            name='discipline',
        ),
        migrations.AddField(
            model_name='athletes',
            name='discipline',
            field=models.ManyToManyField(blank=True, default=True, to='athletes.Discipline', verbose_name='Дисциплины'),
        ),
    ]
